name: Build Dolphin Web

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install build dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build python3 python3-pip git curl

      # Install Emscripten
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          chmod +x emsdk
          ./emsdk install latest
          ./emsdk activate latest
          chmod +x ./emsdk_env.sh
          echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV

      # Download Dolphin
      - name: Download Dolphin
        run: |
          git clone https://github.com/dolphin-emu/dolphin.git dolphin-src
          cd dolphin-src
          git submodule update --init --recursive

      # Configure Dolphin
      - name: Configure Dolphin
        run: |
          source ./emsdk/emsdk_env.sh
          cd dolphin-src
          mkdir -p build-web
          cd build-web
          emcmake cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_GENERIC=ON \
            -DENABLE_QT=OFF \
            -DENABLE_SDL=OFF \
            -DENABLE_X11=OFF \
            -DENABLE_LTO=OFF \
            -DENABLE_HEADLESS=ON \
            -DUSE_DISCORD_PRESENCE=OFF \
            -DUSE_MGBA=OFF \
            -DZLIB_DONT_USE_X86_FEATURES=ON \
            -DARCH_X86=OFF \
            -DARCH_X86_64=OFF \
            -DBASEARCH_X86_FOUND=OFF

      # Build Dolphin
      - name: Build Dolphin
        run: |
          source ./emsdk/emsdk_env.sh
          cd dolphin-src/build-web
          make -j$(nproc) -i

      # Upload Artifacts
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-web
          path: dolphin-src/build-web
